sudo: required
dist: Trusty
script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-5
  - sudo unlink /usr/bin/gcc
  - sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - git submodule update --remote --recursive
  - make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
