sudo: required

dist: Xenial

script:
  - gcc --version
  - git submodule update --remote --recursive
  - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
